name: KiwiAdmin
main: se.kiwike.yottabyte.KiwiAdmin
version: 3.0.5
website: http://kiwike.se
author: yottabyte
description: >
             Admin plugin for Bukkit, adds important functions like kicking and banning.
commands:
  kick:
    description: Kick a player
    usage: /<command> player [reason] - Kick a player
  tempban:
    description: Temporarily ban a player
    usage: /<command> player time timeform [reason] - Temporarily ban a player
  ban:
    description: Ban a player
    usage: /<command> player [reason] - Ban a player
  unban:
    description: Unban a player
    usage: /<command> player - Unban a player
  checkban:
    description: Check if a player is banned
    usage: /<command>
  reloadka:
    description: Reload the banlist
    usage: /<command>
  ipban:
    description: IP-ban a player
    usage: /<command> player [reason]
  exportbans:
    description: Export bans to banned-players.txt
    usage: /<command>
  warn:
    description: Warn a player
    usage: /<command> player [reason] - Warn a player
  editban:
    description: Edit a ban
    usage: /<command> <list/load/id/save/view/reason/time/cancel>
    aliases: [eb,eban]